development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: influencers_development
  pool:     8
  username: FWallace
  password:

test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: influencers_test
  pool:     8
  username: FWallace
  password:

production:
  url:  <%= Rails.application.credentials.production[:database_url] %>
  pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 8 %>
