# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9142d27a204d5c361de586a3658700af253be210445b52be0fb6c1016401bd22c9052fb50cabf34d54b37320d5787739bd30bd7cd88a2a89750421dd47fef7b4

test:
  secret_key_base: cb2fa446ab64386ace274ab028f756bb272fec4a80876b91160f05d4635971281512107129d54c0fc0674d11671a05a6e88f72d5ccef92bb8419bb9a53da5bfa

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
